### ISSUE TITLE
TokenView scrollable horizontal at initialization

### ISSUE THREAD

**Issue by mina-kleid** [NitWitStudios/NWSTokenView#16]
The token view width is very big and scrollable at initialization. After adding a new token everything works fine

**Comment by ghost** [comment]
@mina-zaki Thanks for the catch. I noticed this in other projects ever since iOS 10 / Swift 3 came out. 

Seems that you must call `layoutIfNeeded` on views prior to setting any UI elements within `viewDidLoad` / `viewWillAppear`. These methods no longer guarantee that a view has been laid out.

**Change your setup to something like this in the view controller class you use the token view:**

```
class NWSTokenViewExampleViewController: UIViewController, NWSTokenDataSource, NWSTokenDelegate {
    override func viewDidLoad() {
        super.viewDidLoad()

        tokenView.layoutIfNeeded() // Call this to properly setup tokenView's constraints
        tokenView.dataSource = self
        tokenView.delegate = self
        tokenView.reloadData()
    }
}
```

**Comment by mina-kleid** [comment]
@NitWitStudios unfortunately didnt help 😞

**Comment by ghost** [comment]
@mina-zaki Did you also update to the latest cocoapod, 2.0.1? I did make a couple other changes that may resolve the issue.

**Comment by ghost** [comment]
If you are still having issues, can you provide me with some sample code?

**Comment by mina-kleid** [comment]
The cocoapod update worked perfectly, thanks a lot
