### ISSUE TITLE
Swift 4.0 support

### ISSUE THREAD

**Issue by nyekimov** [NitWitStudios/NWSTokenView#22]
Some code isn't compatible with swift 4. Do you have any plans on supporting the project or is it abandoned? Not sure if I should push a PR with a fix.

**Comment by ghost** [comment]
@nyekimov Thanks for your feedback! Yes, I still continue supporting this library but just haven't had time to run it against Swift 4 and apply the fixes. You are more than welcome to make the fixes yourself and create a PR (in fact I would greatly appreciate it!). Otherwise I will try to do it myself in the next few weeks when my schedule opens up a bit more.
Cheers! 🍻

**Comment by mike011** [comment]
@ghost I've pushed up a PR to upgrade the pod to support Swift 4.2 - https://github.com/Appmazo/NWSTokenView/pull/26. Could you please review it?

Thanks

**Comment by JimmyJammed** [comment]
@nyekimov Swift 4.2 is now supported thanks to @mike011 (#26 ).
Cheers 🍻
